import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
import { SignIn, SignInButton, SignOutButton, SignUp, useUser } from "@clerk/nextjs";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
   const user = useUser()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
      <h1> Sign up</h1>
      <SignUp path="/sign-up" routing="path" signInUrl="/sign-in" />
      <h1> Sign in 1</h1>
      <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      <h1> Sign in 2</h1>
      <hr />
      <div>
        {!user.isSignedIn &&  <SignInButton />}
        {user.isSignedIn &&  <SignOutButton />}
      </div>
      

      </main>
    </>
  );
};

export default Home;
